// src/pages/IdCards.tsx
import { useState } from 'react';
import { Download, Printer, QrCode, ChevronLeft, ChevronRight, CreditCard, Smartphone, RotateCw, ShieldCheck, Search } from 'lucide-react';
import Card from '../components/ui/Card';
import { StatusBadge, DegreeBadge } from '../components/ui/Badge';
import Button from '../components/ui/Button';
import Avatar from '../components/ui/Avatar';

import CredentialValidatorModal from '../components/modals/CredentialValidatorModal';
import { mockMembers, currentUser } from '../data/mockData';
import type { Member } from '../types';
import './IdCards.css';

type CardMode = 'vertical' | 'horizontal';

interface IdCardsProps {
  initialMember?: Member | null;
}

export default function IdCards({ initialMember }: IdCardsProps) {
  const [cardMode, setCardMode] = useState<CardMode>('vertical');
  const [selectedIdx, setSelectedIdx] = useState<number>(() => {
    if (initialMember) {
      const idx = mockMembers.findIndex(m => m.id === initialMember.id);
      return idx >= 0 ? idx : 0;
    }
    return 0;
  });
  const [isFlipped, setIsFlipped] = useState(false);
  const [showValidator, setShowValidator] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');

  const filteredMembers = mockMembers.filter(m =>
    m.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    m.cim.includes(searchTerm) ||
    (m.office || '').toLowerCase().includes(searchTerm.toLowerCase())
  );

  const currentMember = filteredMembers[selectedIdx] || mockMembers[0] || {
    ...currentUser,
    avatar: currentUser.avatar,
    office: currentUser.role,
    cim: currentUser.cim,
    phone: currentUser.phone,
    email: currentUser.email,
    joinedAt: currentUser.joinedAt,
    lodge: currentUser.lodge || '',
    specialty: currentUser.specialty,
  };

  const degreeLabels: Record<number, string> = {
    1: 'Aprendiz Maçom',
    2: 'Companheiro Maçom',
    3: 'Mestre Maçom',
    33: 'REAA – 33° Grau',
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="idcards-page page-enter">
      {/* Toolbar */}
      <div className="idcards-toolbar">
        <div className="idcards-mode-tabs">
          <button
            className={`idcards-mode-tab ${cardMode === 'vertical' ? 'idcards-mode-tab--active' : ''}`}
            onClick={() => setCardMode('vertical')}
            id="card-mode-vertical"
          >
            <Smartphone size={16} />
            Digital (Vertical)
          </button>
          <button
            className={`idcards-mode-tab ${cardMode === 'horizontal' ? 'idcards-mode-tab--active' : ''}`}
            onClick={() => setCardMode('horizontal')}
            id="card-mode-horizontal"
          >
            <CreditCard size={16} />
            Impressão PVC (Horizontal)
          </button>
        </div>
        <div style={{ display: 'flex', gap: 8, marginLeft: 'auto', flexWrap: 'wrap' }}>
          <Button variant="outline" size="sm" icon={<ShieldCheck size={14} />} onClick={() => setShowValidator(true)}>
            Validar Autenticidade
          </Button>
          <Button variant="outline" size="sm" icon={<Printer size={14} />} onClick={handlePrint}>
            Imprimir
          </Button>
          <Button variant="accent" size="sm" icon={<Download size={14} />} onClick={handlePrint}>
            Baixar PDF
          </Button>
        </div>
      </div>

      <div className="idcards-content">
        {/* Member selector */}
        <Card padding="none" className="idcards-selector">
          <div className="idcards-selector-header">
            <div className="idcards-selector-title">Selecionar Irmão</div>
            <div className="idcards-selector-count">{filteredMembers.length} membros</div>
          </div>
          
          <div className="idcards-search-box">
            <Search size={14} style={{ color: 'var(--color-text-secondary)', marginRight: 6 }} />
            <input
              type="text"
              placeholder="Buscar por nome, CIM ou cargo..."
              value={searchTerm}
              onChange={e => {
                setSearchTerm(e.target.value);
                setSelectedIdx(0);
              }}
              className="idcards-search-input"
            />
          </div>

          <div className="idcards-selector-list">
            {filteredMembers.map((m, idx) => (
              <button
                key={m.id}
                className={`idcards-selector-item ${idx === selectedIdx ? 'idcards-selector-item--active' : ''}`}
                onClick={() => {
                  setSelectedIdx(idx);
                  setIsFlipped(false);
                }}
                id={`select-member-${m.id}`}
              >
                <Avatar initials={m.avatar} size="sm" status={m.status} />
                <div className="idcards-selector-info">
                  <div className="idcards-selector-name">{m.name.replace('Ir. ', '')}</div>
                  <div className="idcards-selector-role">{m.office}</div>
                </div>
                <DegreeBadge degree={m.degree} />
              </button>
            ))}
            {filteredMembers.length === 0 && (
              <div style={{ padding: 24, textAlign: 'center', color: 'var(--color-text-secondary)', fontSize: '0.85rem' }}>
                Nenhum membro encontrado.
              </div>
            )}
          </div>
        </Card>

        {/* Card preview */}
        <div className="idcards-preview-area">
          {cardMode === 'vertical' ? (
            <VerticalCard
              member={currentMember}
              degreeLabels={degreeLabels}
              isFlipped={isFlipped}
              onFlip={() => setIsFlipped(!isFlipped)}
              onValidate={() => setShowValidator(true)}
            />
          ) : (
            <HorizontalCard
              member={currentMember}
              degreeLabels={degreeLabels}
              onValidate={() => setShowValidator(true)}
            />
          )}

          {/* Navigation */}
          <div className="idcards-nav">
            <Button
              variant="outline"
              size="sm"
              icon={<ChevronLeft size={14} />}
              onClick={() => {
                setSelectedIdx(Math.max(0, selectedIdx - 1));
                setIsFlipped(false);
              }}
              disabled={selectedIdx === 0}
            >
              Anterior
            </Button>
            <span className="idcards-nav-count">{selectedIdx + 1} / {filteredMembers.length}</span>
            <Button
              variant="outline"
              size="sm"
              iconRight={<ChevronRight size={14} />}
              onClick={() => {
                setSelectedIdx(Math.min(filteredMembers.length - 1, selectedIdx + 1));
                setIsFlipped(false);
              }}
              disabled={selectedIdx === filteredMembers.length - 1}
            >
              Próximo
            </Button>
          </div>
        </div>

        {/* Info panel */}
        <Card padding="md" className="idcards-info-panel">
          <div className="idcards-info-title">Dados da Carteirinha Maçônica</div>
          <div className="idcards-info-grid">
            <div className="idcards-info-item">
              <div className="idcards-info-label">Portador</div>
              <div className="idcards-info-value">{currentMember.name}</div>
            </div>
            <div className="idcards-info-item">
              <div className="idcards-info-label">CIM</div>
              <div className="idcards-info-value"><code>{currentMember.cim}</code></div>
            </div>
            <div className="idcards-info-item">
              <div className="idcards-info-label">Cargo</div>
              <div className="idcards-info-value">{currentMember.office}</div>
            </div>
            <div className="idcards-info-item">
              <div className="idcards-info-label">Grau</div>
              <div className="idcards-info-value">{degreeLabels[currentMember.degree] || `${currentMember.degree}º Grau`}</div>
            </div>
            <div className="idcards-info-item">
              <div className="idcards-info-label">Status Quitação</div>
              <StatusBadge status={currentMember.status} />
            </div>
            <div className="idcards-info-item">
              <div className="idcards-info-label">Validade</div>
              <div className="idcards-info-value">31/12/2026</div>
            </div>
          </div>

          <div className="idcards-qr-info">
            <div className="idcards-qr-title">Verificação de Autenticidade</div>
            <div className="idcards-qr-sub">
              A carteirinha digital possui validação via QR Code dinâmico conectado diretamente aos servidores do Grande Oriente.
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginTop: 16 }}>
            {cardMode === 'vertical' && (
              <Button variant="outline" fullWidth icon={<RotateCw size={15} />} onClick={() => setIsFlipped(!isFlipped)}>
                {isFlipped ? 'Ver Frente da Carteirinha' : 'Girar Carteirinha (Ver Verso)'}
              </Button>
            )}
            <Button variant="primary" fullWidth icon={<QrCode size={15} />} onClick={() => setShowValidator(true)}>
              Simular Leitura do QR Code
            </Button>
          </div>
        </Card>
      </div>

      {/* Credential Validator Modal */}
      {showValidator && (
        <CredentialValidatorModal
          member={currentMember}
          onClose={() => setShowValidator(false)}
        />
      )}
    </div>
  );
}

function VerticalCard({
  member,
  degreeLabels,
  isFlipped,
  onFlip,
  onValidate,
}: {
  member: Member;
  degreeLabels: Record<number, string>;
  isFlipped: boolean;
  onFlip: () => void;
  onValidate: () => void;
}) {
  return (
    <div className={`card-flip-container ${isFlipped ? 'flipped' : ''}`} onClick={onFlip}>
      <div className="card-flip-inner">
        
        {/* FRONT SIDE */}
        <div className="card-flip-front">
          <svg className="card-watermark-seal" viewBox="0 0 100 100">
            <circle cx="50" cy="50" r="45" fill="none" stroke="currentColor" strokeWidth="3" />
            <polygon points="50,15 80,75 20,75" fill="none" stroke="currentColor" strokeWidth="2.5" />
            <polygon points="50,85 20,25 80,25" fill="none" stroke="currentColor" strokeWidth="2.5" />
          </svg>
          
          <div className="card-ref-header">
            <div className="card-ref-header-left">
              <div className="card-ref-logo">
                <svg viewBox="0 0 100 100" style={{ width: '100%', height: '100%', borderRadius: '50%', background: '#FAF7F2' }}>
                  <circle cx="50" cy="50" r="40" fill="none" stroke="#B45309" strokeWidth="4" />
                  <polygon points="50,20 75,70 25,70" fill="none" stroke="#B45309" strokeWidth="3" />
                </svg>
              </div>
              <div>
                <div className="card-ref-title">GOMB</div>
                <div className="card-ref-subtitle">MARANHÃO E BALSAS</div>
              </div>
            </div>
            <div className="card-ref-badge">REGULAR</div>
          </div>

          <div className="card-ref-photo-box">
            <div style={{ width: 105, height: 125, margin: '0 auto' }}>
              <Avatar initials={member.avatar} size="xl" gradient />
            </div>
          </div>

          <div className="card-ref-name">{member.name}</div>
          <div className="card-ref-degree">{degreeLabels[member.degree] || `${member.degree}º Grau`} - {member.office}</div>

          <div className="card-ref-grid">
            <div className="card-ref-field">
              <span className="card-ref-label">CIM</span>
              <span className="card-ref-val">{member.cim}</span>
            </div>
            <div className="card-ref-field">
              <span className="card-ref-label">Iniciação</span>
              <span className="card-ref-val">{new Date(member.joinedAt).toLocaleDateString('pt-BR')}</span>
            </div>
            <div className="card-ref-field card-ref-full-col">
              <span className="card-ref-label">Loja</span>
              <span className="card-ref-val">{member.lodge || 'A.R.L.S. União Fraternal Nº 001'}</span>
            </div>
          </div>

          <div className="card-ref-footer">
            <span className="card-ref-motto">LIBERTAS QUAE SERA TAMEN</span>
            <span className="card-ref-affil">COMAB</span>
          </div>
        </div>

        {/* BACK SIDE */}
        <div className="card-flip-back">
          <div className="card-back-header">
            CERTIFICADO DE REGULARIDADE MAÇÔNICA
          </div>

          <div style={{ fontSize: '0.62rem', color: '#1E293B', marginTop: 12, lineHeight: 1.4 }}>
            Certificamos que o Irmão <strong>{member.name}</strong> é membro ativo e regular do quadro de obreiros desta augusta oficina, no gozo pleno de seus direitos maçônicos.
          </div>

          <div className="card-back-qr-box" onClick={(e) => { e.stopPropagation(); onValidate(); }}>
            <QRCodeSVG size={90} />
          </div>
          <div className="card-back-qr-sub">Escaneie o código acima para validar a autenticidade desta credencial digital.</div>

          <div className="card-back-signatures">
            <div>
              <div className="card-back-sig-line" />
              <div className="card-back-sig-title">Ir. Venerável Mestre</div>
              <div className="card-back-sig-sub">Venerável Mestre</div>
            </div>
            <div>
              <div className="card-back-sig-line" />
              <div className="card-back-sig-title">Ir. Secretário</div>
              <div className="card-back-sig-sub">Guardador dos Selos</div>
            </div>
          </div>
          
          <div className="card-ref-footer" style={{ marginTop: 12 }}>
            <span className="card-ref-affil">Validade: 31/12/2026</span>
          </div>
        </div>

      </div>
    </div>
  );
}

function HorizontalCard({
  member,
  degreeLabels,
  onValidate,
}: {
  member: Member;
  degreeLabels: Record<number, string>;
  onValidate: () => void;
}) {
  return (
    <div className="horizontal-cards-pair">
      {/* Front PVC */}
      <div className="h-card-frame">
        <svg className="card-watermark-seal" viewBox="0 0 100 100" style={{ left: '70%', top: '50%' }}>
          <circle cx="50" cy="50" r="45" fill="none" stroke="currentColor" strokeWidth="3" />
          <polygon points="50,15 80,75 20,75" fill="none" stroke="currentColor" strokeWidth="2.5" />
          <polygon points="50,85 20,25 80,25" fill="none" stroke="currentColor" strokeWidth="2.5" />
        </svg>

        <div className="h-card-left-col">
          <Avatar initials={member.avatar} size="xl" gradient />
          <div className="card-ref-badge" style={{ marginTop: 12 }}>REGULAR</div>
        </div>
        
        <div className="h-card-right-col">
          <div className="card-ref-header" style={{ paddingBottom: 6, marginBottom: 8 }}>
            <div className="card-ref-header-left">
              <div className="card-ref-logo">
                <svg viewBox="0 0 100 100" style={{ width: '100%', height: '100%', borderRadius: '50%', background: '#FAF7F2' }}>
                  <circle cx="50" cy="50" r="40" fill="none" stroke="#B45309" strokeWidth="4" />
                </svg>
              </div>
              <div>
                <div className="card-ref-title">GOMB</div>
                <div className="card-ref-subtitle">GRANDE ORIENTE DO MARANHÃO E BALSAS</div>
              </div>
            </div>
          </div>

          <div className="card-ref-name" style={{ fontSize: '1.25rem' }}>{member.name}</div>
          <div className="card-ref-degree">{degreeLabels[member.degree] || `${member.degree}º Grau`} - {member.office}</div>

          <div className="card-ref-grid" style={{ marginTop: 'auto', padding: '8px 12px' }}>
            <div className="card-ref-field">
              <span className="card-ref-label">CIM</span>
              <span className="card-ref-val">{member.cim}</span>
            </div>
            <div className="card-ref-field">
              <span className="card-ref-label">Iniciação</span>
              <span className="card-ref-val">{new Date(member.joinedAt).toLocaleDateString('pt-BR')}</span>
            </div>
            <div className="card-ref-field card-ref-full-col">
              <span className="card-ref-label">Loja</span>
              <span className="card-ref-val">{member.lodge || 'A.R.L.S. União Fraternal Nº 001'}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Back PVC */}
      <div className="h-card-frame" style={{ flexDirection: 'row-reverse' }}>
        <div className="h-card-left-col" onClick={onValidate} style={{ cursor: 'pointer', background: 'white', padding: 8, borderRadius: 12, height: 'fit-content', border: '1px solid #E2D9C8', alignSelf: 'center' }}>
          <QRCodeSVG size={90} />
          <div style={{ fontSize: '0.45rem', textAlign: 'center', marginTop: 4, color: '#64748B' }}>SCAN PARA VALIDAR</div>
        </div>
        
        <div className="h-card-right-col">
          <div className="card-back-header">CERTIFICADO DE IDENTIDADE MAÇÔNICA</div>
          <div style={{ fontSize: '0.62rem', color: '#1E293B', marginTop: 12, lineHeight: 1.4 }}>
            O titular desta credencial está em pleno gozo de seus direitos maçônicos perante o Grande Oriente e a {member.lodge || 'sua Loja'}.
          </div>
          
          <div className="card-back-signatures" style={{ marginTop: 'auto' }}>
            <div>
              <div className="card-back-sig-line" />
              <div className="card-back-sig-title">Ir. Venerável Mestre</div>
            </div>
            <div>
              <div className="card-back-sig-line" />
              <div className="card-back-sig-title">Ir. Secretário</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// Simple SVG QR code simulation
function QRCodeSVG({ size = 100 }: { size?: number }) {
  const cells = 10;
  const cellSize = size / cells;
  const pattern = Array.from({ length: cells * cells }, (_, i) => {
    const row = Math.floor(i / cells);
    const col = i % cells;
    const isCorner = (row < 3 && col < 3) || (row < 3 && col >= cells - 3) || (row >= cells - 3 && col < 3);
    return isCorner || Math.random() > 0.45;
  });

  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} style={{ display: 'block', borderRadius: 6, background: '#fff', padding: 4 }}>
      <rect width={size} height={size} fill="white" />
      {pattern.map((filled, i) => {
        const row = Math.floor(i / cells);
        const col = i % cells;
        return filled ? (
          <rect
            key={i}
            x={col * cellSize + 0.5}
            y={row * cellSize + 0.5}
            width={cellSize - 1}
            height={cellSize - 1}
            fill="#0F172A"
            rx={1}
          />
        ) : null;
      })}
    </svg>
  );
}

// src/pages/IdCards.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { Download, Printer, QrCode, ChevronLeft, ChevronRight, CreditCard, Smartphone, RotateCw, ShieldCheck, Search } from 'lucide-vue-next'
import Card from '../components/ui/Card.vue'
import StatusBadge from '../components/ui/StatusBadge.vue'
import DegreeBadge from '../components/ui/DegreeBadge.vue'
import Button from '../components/ui/Button.vue'
import Avatar from '../components/ui/Avatar.vue'
import CredentialValidatorModal from '../components/modals/CredentialValidatorModal.vue'
import { mockMembers, currentUser } from '../data/mockData'
import type { Member } from '../types'
import './IdCards.css'

const props = defineProps<{
  initialMember?: Member | null
}>()

const cardMode = ref<'vertical' | 'horizontal'>('vertical')
const selectedIdx = ref(0)
const isFlipped = ref(false)
const showValidator = ref(false)
const searchTerm = ref('')

if (props.initialMember) {
  const idx = mockMembers.findIndex(m => m.id === props.initialMember!.id)
  if (idx >= 0) {
    selectedIdx.value = idx
  }
}

const filteredMembers = computed(() => {
  return mockMembers.filter(m =>
    m.name.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
    m.cim.includes(searchTerm.value) ||
    (m.office || '').toLowerCase().includes(searchTerm.value.toLowerCase())
  )
})

const currentMember = computed(() => {
  return filteredMembers.value[selectedIdx.value] || mockMembers[0] || {
    ...currentUser,
    avatar: currentUser.avatar,
    office: currentUser.role,
    cim: currentUser.cim,
    phone: currentUser.phone,
    email: currentUser.email,
    joinedAt: currentUser.joinedAt,
    lodge: currentUser.lodge || '',
    specialty: currentUser.specialty,
  }
})

const degreeLabels: Record<number, string> = {
  1: 'Aprendiz Maçom',
  2: 'Companheiro Maçom',
  3: 'Mestre Maçom',
  33: 'REAA – 33° Grau',
}

function handlePrint() {
  window.print()
}

// QRCode simulation
function getQrPattern(size: number) {
  const cells = 10
  const pattern = Array.from({ length: cells * cells }, (_, i) => {
    const row = Math.floor(i / cells)
    const col = i % cells
    const isCorner = (row < 3 && col < 3) || (row < 3 && col >= cells - 3) || (row >= cells - 3 && col < 3)
    return isCorner || Math.random() > 0.45
  })
  return { cells, pattern }
}
const qrPattern = getQrPattern(100)
</script>

<template>
  <div class="idcards-page page-enter">
    <!-- Toolbar -->
    <div class="idcards-toolbar">
      <div class="idcards-mode-tabs">
        <button
          :class="['idcards-mode-tab', cardMode === 'vertical' ? 'idcards-mode-tab--active' : '']"
          @click="cardMode = 'vertical'"
          id="card-mode-vertical"
        >
          <Smartphone :size="16" />
          Digital (Vertical)
        </button>
        <button
          :class="['idcards-mode-tab', cardMode === 'horizontal' ? 'idcards-mode-tab--active' : '']"
          @click="cardMode = 'horizontal'"
          id="card-mode-horizontal"
        >
          <CreditCard :size="16" />
          Impressão PVC (Horizontal)
        </button>
      </div>
      <div style="display: flex; gap: 8px; margin-left: auto; flex-wrap: wrap;">
        <Button variant="outline" size="sm" @click="showValidator = true">
          <template #icon><ShieldCheck :size="14" /></template>
          Validar Autenticidade
        </Button>
        <Button variant="outline" size="sm" @click="handlePrint">
          <template #icon><Printer :size="14" /></template>
          Imprimir
        </Button>
        <Button variant="accent" size="sm" @click="handlePrint">
          <template #icon><Download :size="14" /></template>
          Baixar PDF
        </Button>
      </div>
    </div>

    <div class="idcards-content">
      <!-- Member selector -->
      <Card padding="none" class="idcards-selector">
        <div class="idcards-selector-header">
          <div class="idcards-selector-title">Selecionar Irmão</div>
          <div class="idcards-selector-count">{{ filteredMembers.length }} membros</div>
        </div>
        
        <div class="idcards-search-box">
          <Search :size="14" style="color: var(--color-text-secondary); margin-right: 6px;" />
          <input
            type="text"
            placeholder="Buscar por nome, CIM ou cargo..."
            v-model="searchTerm"
            @input="selectedIdx = 0"
            class="idcards-search-input"
          />
        </div>

        <div class="idcards-selector-list">
          <button
            v-for="(m, idx) in filteredMembers"
            :key="m.id"
            :class="['idcards-selector-item', idx === selectedIdx ? 'idcards-selector-item--active' : '']"
            @click="selectedIdx = idx; isFlipped = false"
            :id="`select-member-${m.id}`"
          >
            <Avatar :initials="m.avatar" size="sm" :status="m.status" />
            <div class="idcards-selector-info">
              <div class="idcards-selector-name">{{ m.name.replace('Ir. ', '') }}</div>
              <div class="idcards-selector-role">{{ m.office }}</div>
            </div>
            <DegreeBadge :degree="m.degree" />
          </button>
          <div v-if="filteredMembers.length === 0" style="padding: 24px; text-align: center; color: var(--color-text-secondary); font-size: 0.85rem;">
            Nenhum membro encontrado.
          </div>
        </div>
      </Card>

      <!-- Card preview -->
      <div class="idcards-preview-area">
        
        <!-- VERTICAL CARD -->
        <div v-if="cardMode === 'vertical'" :class="['card-flip-container', isFlipped ? 'flipped' : '']" @click="isFlipped = !isFlipped">
          <div class="card-flip-inner">
            <!-- FRONT SIDE -->
            <div class="card-flip-front">
              <svg class="card-watermark-seal" viewBox="0 0 100 100">
                <circle cx="50" cy="50" r="45" fill="none" stroke="currentColor" stroke-width="3" />
                <polygon points="50,15 80,75 20,75" fill="none" stroke="currentColor" stroke-width="2.5" />
                <polygon points="50,85 20,25 80,25" fill="none" stroke="currentColor" stroke-width="2.5" />
              </svg>
              
              <div class="card-ref-header">
                <div class="card-ref-header-left">
                  <div class="card-ref-logo">
                    <svg viewBox="0 0 100 100" style="width: 100%; height: 100%; border-radius: 50%; background: #FAF7F2;">
                      <circle cx="50" cy="50" r="40" fill="none" stroke="#B45309" stroke-width="4" />
                      <polygon points="50,20 75,70 25,70" fill="none" stroke="#B45309" stroke-width="3" />
                    </svg>
                  </div>
                  <div>
                    <div class="card-ref-title">GOMB</div>
                    <div class="card-ref-subtitle">MARANHÃO E BALSAS</div>
                  </div>
                </div>
                <div class="card-ref-badge">REGULAR</div>
              </div>

              <div class="card-ref-photo-box">
                <div style="width: 105px; height: 125px; margin: 0 auto;">
                  <Avatar :initials="currentMember.avatar" size="xl" gradient />
                </div>
              </div>

              <div class="card-ref-name">{{ currentMember.name }}</div>
              <div class="card-ref-degree">{{ degreeLabels[currentMember.degree] || `${currentMember.degree}º Grau` }} - {{ currentMember.office }}</div>

              <div class="card-ref-grid">
                <div class="card-ref-field">
                  <span class="card-ref-label">CIM</span>
                  <span class="card-ref-val">{{ currentMember.cim }}</span>
                </div>
                <div class="card-ref-field">
                  <span class="card-ref-label">Iniciação</span>
                  <span class="card-ref-val">{{ new Date(currentMember.joinedAt).toLocaleDateString('pt-BR') }}</span>
                </div>
                <div class="card-ref-field card-ref-full-col">
                  <span class="card-ref-label">Loja</span>
                  <span class="card-ref-val">{{ currentMember.lodge || 'A.R.L.S. União Fraternal Nº 001' }}</span>
                </div>
              </div>

              <div class="card-ref-footer">
                <span class="card-ref-motto">LIBERTAS QUAE SERA TAMEN</span>
                <span class="card-ref-affil">COMAB</span>
              </div>
            </div>

            <!-- BACK SIDE -->
            <div class="card-flip-back">
              <div class="card-back-header">
                CERTIFICADO DE REGULARIDADE MAÇÔNICA
              </div>

              <div style="font-size: 0.62rem; color: #1E293B; margin-top: 12px; line-height: 1.4;">
                Certificamos que o Irmão <strong>{{ currentMember.name }}</strong> é membro ativo e regular do quadro de obreiros desta augusta oficina, no gozo pleno de seus direitos maçônicos.
              </div>

              <div class="card-back-qr-box" @click.stop="showValidator = true">
                <!-- QR Code SVG Simulation -->
                <svg width="90" height="90" viewBox="0 0 90 90" style="display: block; border-radius: 6px; background: #fff; padding: 4px;">
                  <rect width="90" height="90" fill="white" />
                  <template v-for="(filled, i) in qrPattern.pattern" :key="i">
                    <rect
                      v-if="filled"
                      :x="(i % qrPattern.cells) * (90/qrPattern.cells) + 0.5"
                      :y="Math.floor(i / qrPattern.cells) * (90/qrPattern.cells) + 0.5"
                      :width="(90/qrPattern.cells) - 1"
                      :height="(90/qrPattern.cells) - 1"
                      fill="#0F172A"
                      rx="1"
                    />
                  </template>
                </svg>
              </div>
              <div class="card-back-qr-sub">Escaneie o código acima para validar a autenticidade desta credencial digital.</div>

              <div class="card-back-signatures">
                <div>
                  <div class="card-back-sig-line" />
                  <div class="card-back-sig-title">Ir. Venerável Mestre</div>
                  <div class="card-back-sig-sub">Venerável Mestre</div>
                </div>
                <div>
                  <div class="card-back-sig-line" />
                  <div class="card-back-sig-title">Ir. Secretário</div>
                  <div class="card-back-sig-sub">Guardador dos Selos</div>
                </div>
              </div>
              
              <div class="card-ref-footer" style="margin-top: 12px;">
                <span class="card-ref-affil">Validade: 31/12/2026</span>
              </div>
            </div>
          </div>
        </div>

        <!-- HORIZONTAL CARD -->
        <div v-else class="horizontal-cards-pair">
          <!-- Front PVC -->
          <div class="h-card-frame">
            <svg class="card-watermark-seal" viewBox="0 0 100 100" style="left: 70%; top: 50%;">
              <circle cx="50" cy="50" r="45" fill="none" stroke="currentColor" stroke-width="3" />
              <polygon points="50,15 80,75 20,75" fill="none" stroke="currentColor" stroke-width="2.5" />
              <polygon points="50,85 20,25 80,25" fill="none" stroke="currentColor" stroke-width="2.5" />
            </svg>

            <div class="h-card-left-col">
              <Avatar :initials="currentMember.avatar" size="xl" gradient />
              <div class="card-ref-badge" style="margin-top: 12px;">REGULAR</div>
            </div>
            
            <div class="h-card-right-col">
              <div class="card-ref-header" style="padding-bottom: 6px; margin-bottom: 8px;">
                <div class="card-ref-header-left">
                  <div class="card-ref-logo">
                    <svg viewBox="0 0 100 100" style="width: 100%; height: 100%; border-radius: 50%; background: #FAF7F2;">
                      <circle cx="50" cy="50" r="40" fill="none" stroke="#B45309" stroke-width="4" />
                    </svg>
                  </div>
                  <div>
                    <div class="card-ref-title">GOMB</div>
                    <div class="card-ref-subtitle">GRANDE ORIENTE DO MARANHÃO E BALSAS</div>
                  </div>
                </div>
              </div>

              <div class="card-ref-name" style="font-size: 1.25rem;">{{ currentMember.name }}</div>
              <div class="card-ref-degree">{{ degreeLabels[currentMember.degree] || `${currentMember.degree}º Grau` }} - {{ currentMember.office }}</div>

              <div class="card-ref-grid" style="margin-top: auto; padding: 8px 12px;">
                <div class="card-ref-field">
                  <span class="card-ref-label">CIM</span>
                  <span class="card-ref-val">{{ currentMember.cim }}</span>
                </div>
                <div class="card-ref-field">
                  <span class="card-ref-label">Iniciação</span>
                  <span class="card-ref-val">{{ new Date(currentMember.joinedAt).toLocaleDateString('pt-BR') }}</span>
                </div>
                <div class="card-ref-field card-ref-full-col">
                  <span class="card-ref-label">Loja</span>
                  <span class="card-ref-val">{{ currentMember.lodge || 'A.R.L.S. União Fraternal Nº 001' }}</span>
                </div>
              </div>
            </div>
          </div>

          <!-- Back PVC -->
          <div class="h-card-frame" style="flex-direction: row-reverse;">
            <div class="h-card-left-col" @click="showValidator = true" style="cursor: pointer; background: white; padding: 8px; border-radius: 12px; height: fit-content; border: 1px solid #E2D9C8; align-self: center;">
              <!-- QR Code SVG Simulation -->
              <svg width="90" height="90" viewBox="0 0 90 90" style="display: block; border-radius: 6px; background: #fff; padding: 4px;">
                <rect width="90" height="90" fill="white" />
                <template v-for="(filled, i) in qrPattern.pattern" :key="i">
                  <rect
                    v-if="filled"
                    :x="(i % qrPattern.cells) * (90/qrPattern.cells) + 0.5"
                    :y="Math.floor(i / qrPattern.cells) * (90/qrPattern.cells) + 0.5"
                    :width="(90/qrPattern.cells) - 1"
                    :height="(90/qrPattern.cells) - 1"
                    fill="#0F172A"
                    rx="1"
                  />
                </template>
              </svg>
              <div style="font-size: 0.45rem; text-align: center; margin-top: 4px; color: #64748B;">SCAN PARA VALIDAR</div>
            </div>
            
            <div class="h-card-right-col">
              <div class="card-back-header">CERTIFICADO DE IDENTIDADE MAÇÔNICA</div>
              <div style="font-size: 0.62rem; color: #1E293B; margin-top: 12px; line-height: 1.4;">
                O titular desta credencial está em pleno gozo de seus direitos maçônicos perante o Grande Oriente e a {{ currentMember.lodge || 'sua Loja' }}.
              </div>
              
              <div class="card-back-signatures" style="margin-top: auto;">
                <div>
                  <div class="card-back-sig-line" />
                  <div class="card-back-sig-title">Ir. Venerável Mestre</div>
                </div>
                <div>
                  <div class="card-back-sig-line" />
                  <div class="card-back-sig-title">Ir. Secretário</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Navigation -->
        <div class="idcards-nav">
          <Button
            variant="outline"
            size="sm"
            @click="selectedIdx = Math.max(0, selectedIdx - 1); isFlipped = false"
            :disabled="selectedIdx === 0"
          >
            <template #icon><ChevronLeft :size="14" /></template>
            Anterior
          </Button>
          <span class="idcards-nav-count">{{ selectedIdx + 1 }} / {{ filteredMembers.length }}</span>
          <Button
            variant="outline"
            size="sm"
            @click="selectedIdx = Math.min(filteredMembers.length - 1, selectedIdx + 1); isFlipped = false"
            :disabled="selectedIdx === filteredMembers.length - 1"
          >
            <template #iconRight><ChevronRight :size="14" /></template>
            Próximo
          </Button>
        </div>
      </div>

      <!-- Info panel -->
      <Card padding="md" class="idcards-info-panel">
        <div class="idcards-info-title">Dados da Carteirinha Maçônica</div>
        <div class="idcards-info-grid">
          <div class="idcards-info-item">
            <div class="idcards-info-label">Portador</div>
            <div class="idcards-info-value">{{ currentMember.name }}</div>
          </div>
          <div class="idcards-info-item">
            <div class="idcards-info-label">CIM</div>
            <div class="idcards-info-value"><code>{{ currentMember.cim }}</code></div>
          </div>
          <div class="idcards-info-item">
            <div class="idcards-info-label">Cargo</div>
            <div class="idcards-info-value">{{ currentMember.office }}</div>
          </div>
          <div class="idcards-info-item">
            <div class="idcards-info-label">Grau</div>
            <div class="idcards-info-value">{{ degreeLabels[currentMember.degree] || `${currentMember.degree}º Grau` }}</div>
          </div>
          <div class="idcards-info-item">
            <div class="idcards-info-label">Status Quitação</div>
            <StatusBadge :status="currentMember.status" />
          </div>
          <div class="idcards-info-item">
            <div class="idcards-info-label">Validade</div>
            <div class="idcards-info-value">31/12/2026</div>
          </div>
        </div>

        <div class="idcards-qr-info">
          <div class="idcards-qr-title">Verificação de Autenticidade</div>
          <div class="idcards-qr-sub">
            A carteirinha digital possui validação via QR Code dinâmico conectado diretamente aos servidores do Grande Oriente.
          </div>
        </div>

        <div style="display: flex; flex-direction: column; gap: 8px; margin-top: 16px;">
          <Button v-if="cardMode === 'vertical'" variant="outline" fullWidth @click="isFlipped = !isFlipped">
            <template #icon><RotateCw :size="15" /></template>
            {{ isFlipped ? 'Ver Frente da Carteirinha' : 'Girar Carteirinha (Ver Verso)' }}
          </Button>
          <Button variant="primary" fullWidth @click="showValidator = true">
            <template #icon><QrCode :size="15" /></template>
            Simular Leitura do QR Code
          </Button>
        </div>
      </Card>
    </div>

    <!-- Credential Validator Modal -->
    <CredentialValidatorModal
      v-if="showValidator"
      :member="currentMember"
      @close="showValidator = false"
    />
  </div>
</template>
